export const SET_MEMBER = "SET_MEMBER";
export const SET_ORGANIZATION = "SET_ORGANIZATION";
export const SET_DASHBOARD_INTERFACE = "SET_DASHBOARD_INTERFACE";
export const UPDATE_ORGANIZATION = "UPDATE_ORGANIZATION";
